# Generated by Django 4.1.6 on 2023-02-17 19:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationImages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3000), size=None)),
                ('location', models.CharField(max_length=120)),
                ('days', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=120)),
                ('isNew', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
