# Generated by Django 4.1.6 on 2023-02-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_listing_locationimagelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='listing',
            name='days',
            field=models.CharField(default='Contact for details', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='listing',
            name='locationImageList',
            field=models.ManyToManyField(blank=True, to='services.images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(default='Contact for details', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
    ]
