# Generated by Django 4.1.6 on 2023-02-18 03:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_images_imageholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='locationImageList',
        ),
        migrations.DeleteModel(
            name='ImageHolder',
        ),
        migrations.AddField(
            model_name='listing',
            name='locationImageList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=2000), default=[], size=None),
        ),
    ]
