# Generated by Django 4.1.6 on 2023-02-18 03:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_listing_locationimagelist_delete_imageholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='locationImageList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=2000), default=list, size=None),
        ),
    ]
